version: '3.8'

services:
  devops-agent:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: AzpAlpineBuildAgent
    restart: always
    networks:
      - devopsagentnetwork
    environment:
      - AZP_URL={ Your Azure DevOps Organization URL }|
      - AZP_TOKEN={ Your Azure DevOps PAT }
      - AZP_AGENT_NAME={ Your Agent Name }
      - AZP_POOL={ Your Agent Pool Name }

networks:
  devopsagentnetwork:
    driver: bridge